BACKGROUND_FILE_PATHS: ['','']
SAMPLE_FILES_PATH: ''
INCLUDE_FILE_NAMES: ['','']
OUTPUT_PATH: ''
OUTPUT_PER_SAMPLE: 60
FRACTION_OF_INCLUDE_FILE: 0.50
DIR_TO_PASS_TO_MODEL: ''
BACKGROUND_FLIP_REQ: True
